// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7c7fEEGli8ua78RoqESVN-JFj3A1rKaY',
    appId: '1:1494408629:android:ec1147de348b59b04dcdfc',
    messagingSenderId: '1494408629',
    projectId: 'e-business-section',
    storageBucket: 'e-business-section.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTwHx8Qt37s3iaIyyF408jUMIgOiyKhmY',
    appId: '1:1494408629:ios:df8cb1c4e22b77e14dcdfc',
    messagingSenderId: '1494408629',
    projectId: 'e-business-section',
    storageBucket: 'e-business-section.firebasestorage.app',
    iosBundleId: 'com.example.sectionweek2',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN-09325oxP90GfPf24FqW0wZ-PqfUxoY',
    appId: '1:1494408629:web:77a27a9e41ec32c44dcdfc',
    messagingSenderId: '1494408629',
    projectId: 'e-business-section',
    authDomain: 'e-business-section.firebaseapp.com',
    storageBucket: 'e-business-section.firebasestorage.app',
    measurementId: 'G-XYFW4S1BHJ',
  );

}